# ==========================================
# 1. KONFIGURASI DATABASE (NEON TECH)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-bold-bird-a1ew3gn6-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8Wtyb1VkwSRf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ==========================================
# 2. KONFIGURASI JWT (INI YANG KURANG TADI)
# ==========================================
# Secret key ini digunakan untuk menanda-tangani token.
# Harus panjang biar aman.
silobur.app.jwtSecret=hnsYVoNwOIkUW0d4gAMyehocZnfVII7blq4OeCE2u2YvxiS58ELvJeaglSl5I8sHD11OPRGM18oCWDcgdfeGkg==
silobur.app.jwtExpirationMs=86400000